name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest tests
        run: |
          python -m pytest test/unit -v --junitxml=reports/pytest.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest results
          path: reports/pytest.xml

  robot-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run robot tests
        run: |
          robot --outputdir reports/robot test/robot

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot results
          path: reports/robot/output.xml
